-- Actra Supabase Database Schema (Multi-Tenant + RLS)

-- Enable uuid-ossp extension for UUID generation if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Settings Table
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, key)
);
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own settings" ON settings FOR ALL USING (auth.uid() = user_id);

-- 2. Bookmarks Table
CREATE TABLE IF NOT EXISTS bookmarks (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  folder_id TEXT,
  date_added BIGINT NOT NULL
);
ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own bookmarks" ON bookmarks FOR ALL USING (auth.uid() = user_id);

-- 3. History Table
CREATE TABLE IF NOT EXISTS history (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT,
  url TEXT NOT NULL,
  visit_time BIGINT NOT NULL
);
ALTER TABLE history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own history" ON history FOR ALL USING (auth.uid() = user_id);

-- 4. Companions Table
CREATE TABLE IF NOT EXISTS companions (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  data JSONB NOT NULL
);
ALTER TABLE companions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own companions" ON companions FOR ALL USING (auth.uid() = user_id);

-- 5. Companion Memory Table
CREATE TABLE IF NOT EXISTS companion_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  companion_id TEXT NOT NULL,
  key TEXT NOT NULL,
  value JSONB,
  UNIQUE(user_id, companion_id, key)
);
ALTER TABLE companion_memory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own companion_memory" ON companion_memory FOR ALL USING (auth.uid() = user_id);

-- 6. Chat Sessions Table
CREATE TABLE IF NOT EXISTS chat_sessions (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  session_data JSONB NOT NULL
);
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own chat_sessions" ON chat_sessions FOR ALL USING (auth.uid() = user_id);

-- 7. Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  log_data JSONB NOT NULL
);
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own audit_logs" ON audit_logs FOR ALL USING (auth.uid() = user_id);

-- 8. Google Auth Tokens Table
CREATE TABLE IF NOT EXISTS google_auth_tokens (
  user_id UUID PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  tokens JSONB NOT NULL
);
ALTER TABLE google_auth_tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own google_auth_tokens" ON google_auth_tokens FOR ALL USING (auth.uid() = user_id);
